stack.yaml

I updated the stack.yml file to the lts-5.0. The library `parseerror-eq-0.1.0.1` is included in this lts, so I think we can remove it from the extra-dependency list in the stack.yml file.

Upgrade to lts-5.0

---

dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs
spec/Configuration/Dotenv/TextSpec.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Parse.hs
src/Configuration/Dotenv/Text.hs

Functions in `System.Environment`, `System.Process` etc. returns or takes environment variables as `String`, not `Text`.
In many cases users will merge them with ones from dotenv, so it'll be better to leave interfaces in plain String for their convenience.

Add Text version of parsefile along with String version

---

.travis.yml
stack.yaml

@jsl This is what I had in mind regarding issue #19 (and https://github.com/stackbuilders/dotenv-hs/issues/19#issuecomment-198982228 in particular).
(Not a big deal, but it takes around eight minutes less to finish all build jobs.)

Remove extra dependencies from stack.yaml

---

.travis.yml
CHANGELOG.md
dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs
src/Configuration/Dotenv/Parse.hs
stack.yaml

Fixes https://github.com/fpco/stackage/issues/2666

Use megaparsec 6.0

---

README.md

We currently don't support empty env vars and it would be a good idea to have this comments in our `README` so that people know what they can do to have empty env vars.

Update README.md to give suggestions about having empty env vars

---

app/Main.hs
dotenv.cabal

Output of the CLI:
```
➜  dotenv-hs git:(add_version_flag) ✗ stack exec dotenv
Missing: (-f|--dotenv DOTENV) PROGRAM
Usage: dotenv [-v|--version] (-f|--dotenv DOTENV) [--example DOTENV_EXAMPLE]
[-o|--overload] PROGRAM [ARG]
Runs PROGRAM after loading options from FILE
➜  dotenv-hs git:(add_version_flag) ✗ stack exec dotenv -- -v
0.5.0.1
➜  dotenv-hs git:(add_version_flag) ✗
```
@juanpaucar Could you take a look, please? To close #60

Add version to the CLI, close #60

---

README.md
app/Main.hs

@juanpaucar Could you take a look, please? It closes #62
This is a workaround since `value` from `optparser-applicative` doesn't work for `some` or `many`.

Allow .env file as default, closes #62

---

src/Configuration/Dotenv/Types.hs

The current module description markup for `Configuration.Dotenv.Types` uses both `{- |` and `--`, which yields:
Instead of (using this change):

Fix module description markup (Configuration.Dotenv.Types)

---

src/Configuration/Dotenv.hs

There are writting `import Configuration.Dotenv (loadFile, defaultConfig)` in README.
But `defaultConfig` is not reexport in `Configuration.Dotenv` module.
Occur error when write Main.hs like README:
```
Main.hs:17:42: error:
Module ‘Configuration.Dotenv’ does not export ‘defaultConfig’
|                             
17 | import           Configuration.Dotenv   (defaultConfig, loadFile)
|                                          ^^^^^^^^^^^^^
```
So, need to explicit reexport `defaultConfig` if not change README.

Reexport defaultConfig

---

CHANGELOG.md
app/Main.hs
dotenv.cabal

The dotenv documentation in Hackage shows that we export everything from out package:
However, people will only need to `import Configuration.Dotenv`.
Therefore, I consider we should hide our other modules in `other-modules`. This could be a breaking change and that is why I updated to `0.7.0.0`.

Hide helper modules in other-modules

---

CHANGELOG.md
dotenv.cabal

* Support for `optparse-applicative-1.5.0`

Update bounds for optparse-applicative

---

.travis.yml
CHANGELOG.md
dotenv.cabal
stack.yaml

Solves #105.
LTS 13.28 was released a few days ago and it also contains all packages marked before as `extra-deps` on `stack.yaml`.

Add support for GHC 8.6

---

CHANGELOG.md
dotenv.cabal

This pull request addresses issue [#107] 
It allows meparsec 8.0.0

[#107] change megaparsec version

---

.travis.yml
README.md
dotenv.cabal

Solves #112 partially.
I configured travis to create a draft release on each merge to a branch (I suspect that will be `master`). 
Resulting draft release: https://github.com/stackbuilders/dotenv-hs/releases/tag/untagged-102599435dcc9f6e17c9
**Note:** I just need to change the branch name, currently it's deploying when something is merged in this branch for testing).

Create static binary linux 64

---

.travis.yml

Solves part of #112 
I'm using `github-release-cli` to deploy the releases.
Example of draft release generated with this feature: https://github.com/stackbuilders/dotenv-hs/releases/tag/untagged-e5b89fbe11e4932ef8a5
We still need to remove the extra notes from previous releases form the ChangeLog.

Format release notes with ChangeLog content

---

.travis.yml

- `after_success` and `before_install` are only executed for **Build Binary** and **Deploy** stages
- Users that fork this repo and lack of AWS won't have failing CI builds
@juanpaucar Could you please take a look?
**NOTE:** You can see the generated configuration  by copying the `.travis.yml` and pasting it [here](https://config.travis-ci.com/explore)

Install and Sync AWS for build binary & deploy

---

CHANGELOG.md
dotenv.cabal

I run some tests locally forcing `optparse-applicative-0.16.0.0` here are the results:
```diff
resolver: lts-13.28
packages:
- '.'
+extra-deps:
+  - optparse-applicative-0.16.0.0
```
Dependencies:
```
➜ stack ls dependencies | grep optparse
optparse-applicative 0.16.0.0
```
Test output:
```
➜ stack test
...
dotenv> Test suite dotenv-test passed
```

[#124] Allow optparse-applicative-0.16.0.0

---

.github/workflows/release-gh.yml

This PR changes the cabal version to 2.4 for the release workflow (as it was in Travis CI) to fix (previous PR #130)

Release to Github workflow. Change Cabal version to 2.4

---

.github/workflows/build-and-test.yml
.github/workflows/release-gh.yml
CHANGELOG.md
dotenv.cabal
stack.yaml
stack.yaml.lock

* Support GHC 9.0.1
* Support older versions of GHC (< 8.6)

Update support for GHC 9.0.1

---

.env
.gitignore
README.md
app/Main.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Parse.hs
src/Configuration/Dotenv/Types.hs

This PR adds the ```--verbose``` flag  which enables the CLI to: 
- Log when variables are loaded
- Adds Monad Reader
This implements issue #146

Feat: Add Verbose option

---

CHANGELOG.md
app/Main.hs
dotenv.cabal
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs

After reviewing the question described by @nsaunders I think it would be best
to return to the initial return value for `loadFile`. It would make more sense
since it's an action that doesn't need to return the list of environment variables
loaded. It's main purpose is to load the envs from a file before running another action.

chore: Go back to previous return type for loadFile

---

dotenv.cabal
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
stack.yaml
stack.yaml.lock

We ran into this bug yesterday and it was super confusing. When a variable present in the `.env` or `.env.example` is pre-set in ENV, the validation has a bug that results in the key being in the "have" side of the equation twice. Since that adds an extra `(+1)` on the length of the "have" vs "need", the condition fails. Combined that with the fact that the error message just dumps out all of the "need" variables (instead of only what is missing) and we were scratching our heads for quite a while.
I recommend reviewing commit by commit. Let me know if you want me to rewrite out the post-factor commits, but I think they're useful enough to at least get your take on. Only the bug-fix commit is the one I'd really like to see landed.
--- …

Fix unexpected error with preset ENV and .env.example

---

dotenv.cabal
spec/Configuration/DotenvSpec.hs
spec/fixtures/.dotenv.dup
src/Configuration/Dotenv.hs

- This PR addresses [issue #121](https://github.com/stackbuilders/dotenv-hs/issues/121)
- Mapping vars before setting in environment using function `nubByLastVar`.
- Added function [`nubByLastVar`](https://github.com/stackbuilders/dotenv-hs/compare/issue-121-dotenv-picks-last-value?expand=1#diff-28752b99ee8c901d2f3dead57a3943b5fe22dc7c15bf7ec272eee5e646f4843fR163) that yields a [`Data.Map`](https://hackage.haskell.org/package/containers-0.4.0.0/docs/Data-Map.html)  from a list and the returns back an ordered list of type `[(String), (String)]`. If the list contains more than one value for the same key, the last value for the key is retained.

Introduced nubByLastVar vars before applying setting.

---

README.md
app/Main.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Types.hs

This PR tackles the feature request outlined in https://github.com/stackbuilders/dotenv-hs/issues/159 
The current Dotenv CLI executes the program regardless of the provided environment variables, even if they are missing or do not meet the required criteria. This behavior poses a concern as it may lead to unintended consequences or errors.
To address this issue, this pull request introduces a new flag  --dry-run that allows users to examine the loaded environment variables without executing the program.

feat: Add --dry-run flag to print out variables without executing the program

---

.all-contributorsrc
README.md

-  Add @CristhianMotoche as a contributor
-  Add @jsl as a contributor
-  Add @mrkkrp as a contributor
-  Add @juanpaucar as a contributor
-  Add @jpvillaisaza as a contributor
-  Add @fujimura as a contributor
-  Add @cptrodolfox as a contributor
-  Add @dbalseiro as a contributor
-  Add @fefi95 as a contributor
-  Add @goetzc as a contributor
-  Add @phadej as a contributor
-  Add @sestrella as a contributor
-  Add @habibalamin as a contributor
-  Add @FranzGB as a contributor
-  Add @pbrisbin as a contributor
-  Add @aloussase as a contributor
-  Add @alexisbcc as a contributor
-  Add @anddriex as a contributor
-  Add @ibarrae as a contributor
-  Add @flandrade as a contributor
-  Add @Jagl257 as a contributor
-  Add @matsubara0507 as a contributor
-  Add @wojtekmach as a contributor

chore: Add All Contributors

---

.github/workflows/build.yml
CHANGELOG.md
dotenv.cabal

- Increase support up to GHC 9.6

chore: Update support up to GHC 9.6 and bump new version 0.12.0.0

---

dotenv.cabal
stack.yaml

#174
**Issue 1: 'ghc-options: -O2' is rarely needed:**
Time tests were conducted using `time cabal build`, yielding the following results:
Without using "-O2":
With the use of "-O2":
From these results, we can see that the use of "-O2" doesn't actually provide any time-related benefits.
**Issue 2: Missing Upper Bounds in Dependency Packages**
Upper bounds were added to the dependencies that required them: "-compat -containers -directory -hspec -shellwords -text". The `gen-bounds` tool was used, as suggested. Tests were conducted via `stack` to assess the compatibility of each of the packages with the upper bounds I set, based on the proposed suggestions using the `gen-bounds` tool."

Added upper limits of required dependencies

---

dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs

This pull request focuses on improving the test suite for the module responsible for parsing files in the dotenv format. The primary enhancement involves replacing a subset of existing unit tests with property-based tests. These new tests leverage randomly generated strings, taking into account the following input characteristics:
- Lines in the format of `key=value`
- Support for comments and blank lines
Let me know your thoughts, @jpvillaisaza, @CristhianMotoche

chore: add property-based tests for Configuration.Dotenv.Parse

---

.github/workflows/build.yml
dotenv.cabal

Thanks to the [get-tested](https://github.com/Kleidukos/get-tested) action, we can automatically generate the matrix of GHC versions to run the CI on. This keeps the `tested-with` versions we set in Cabal files accurate to what is actually being tested in the CI.
Since the action takes one Cabal file as reference, I pointed it to `rollbar-client.cabal` since that is the main library in this repository. In any case, us maintainers need to keep all of the `tested-with` versions in sync across the four Haskell packages we offer in this repository.
This PR also changes the `tested-with` versions of the Cabal in the project to the latest minor versions of GHC 8.10 (the latest GHC 8 version), GHC 9.6 and GHC 9.8 (the two most recent GHC 9 versions).
Closes #189.

Added `kleidukos/get-tested` action to generate CI matrix #64

---

spec/Configuration/Dotenv/TextSpec.hs
spec/fixtures/.dotenv
src/Configuration/Dotenv/Parse.hs

- **test: Introduced tests to validate correct handling of newline characters `\n` and multiline strings in dotenv files.**
- **fix: Implemented parsing of newline and multiline strings in dotenv files accurately**
This pull request addresses issue #186. I wasn't sure if we should parse it as a newline or as a literal string. I decided to go with the latter. But happy to change it if needed. Let me know if you have any feedback.
Additionally, I noticed that our current tests depend heavily on the index of parsed (key, value) pairs, which could make them fragile and prone to breaking with minor changes in the fixture. I propose that we refactor these tests to make them more robust and resilient to changes. I look forward to hearing your thoughts on this.

fix: Correctly parse newline and multiline strings in dotenv files

---

app/Main.hs
dotenv.cabal

This is tackling #160 
I added a separate record `Flags` to hold the flags that can be parsed from a configuration file, tentatively `dotenv.config` in the current directory.
At first, I tried to reuse the `Options` record, but this became messy when dealing with the `program` argument. I could not find a non-hacky way to deal with that and thought that it would be best to have a separate parser for the flags.
Having said that, I extracted the option parsers to separate definitions to reuse as much code as possible and also so that the parsers for flags and options keep in sync.
`applyFlags` takes care of combining the flags from command line arguments and the configuration file. `<>` for list arguments is a natural combination, and I believe `||` for booleans also works correctly.
Some …

Parse configuration file from current directory for additional flags
