stackbuilders/dotenv-hs

spec/Configuration/DotenvSpec.hs

Hi, this library looks great!
I'd like to propose some tidy ups in specs:
- Use `after_` for teardown
- Use `shouldReturn` to assert result of IO action

Tidy up specs

---

.gitignore
stack.yaml

@jsl Could you take a look?
- First, I added stack configuration in order to upload it to Stackage.
- Second, I had to add the capability to set empty environmental variables using System.Posix.Env, because the setEnv function from System.Environment.Compat has an issue when try to set an environmental variable with an empty string (you can read it here http://hackage.haskell.org/package/base-compat-0.8.2/docs/System-Environment-Compat.html#v:setEnv). I wrote three unit test in order to test this.

Add stack and change .gitignore

---

.travis.yml
dotenv.cabal

Change travis stack

---

spec/Configuration/Dotenv/ParseSpec.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs

I'm creating a Foreman clone in Haskell now, and need this function in it. Thanks!

Add loadFile' which returns envs, not loading them

---

app/Main.hs
dotenv.cabal

Allow optparse-applicative 0.13

---

app/Main.hs
dotenv.cabal
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Text.hs

@mrkkrp Does this solve issue #30 ?

Change monad from 'IO' to 'MonadIO m => m'

---

.travis.yml

Add GHC 8.0.1 to the build matrix

---

.travis.yml
dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs
src/Configuration/Dotenv/Parse.hs
stack.yaml

Rewrite parser

---

CHANGELOG.md
dotenv.cabal
spec/Configuration/Dotenv/TextSpec.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs

Almost remove dependency on ‘base-compat’

---

CHANGELOG.md
README.md
dotenv.cabal

Version bump (0.3.3.0)

---

dotenv.cabal
stack.yaml

This change fixes this issue:
https://github.com/fpco/stackage/issues/2569

Loose constraint for optparse-applicative 0.14

---

dotenv.cabal

@juanpaucar Do you think this could solve the issue #58 ?

Add spec/fixtures to cabal file

---

CHANGELOG.md
dotenv.cabal

@juanpaucar Could you take a look, please?

Update version of dotenv

---

CHANGELOG.md
README.md
dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs
spec/Configuration/DotenvSpec.hs
spec/fixtures/.dotenv
src/Configuration/Dotenv/Parse.hs
src/Configuration/Dotenv/ParsedVariable.hs
stack.yaml

@juanpaucar Could you take a look, please? It closes #63 
TODO:

Support command substitution

---

spec/Configuration/Dotenv/ParseSpec.hs
src/Configuration/Dotenv/Parse.hs

In order to solve #70 
@juanpaucar Could you take a look, please?

Allow empty .env files

---

CHANGELOG.md
dotenv.cabal

@juanpaucar I forgot to update the PVP specification. Could you please take a look?

Update PVP small change

---

CHANGELOG.md
dotenv.cabal

This file was missing in the construction of the sdist file.

Add .scheme.yml to .cabal file

---

CHANGELOG.md
README.md
app/Main.hs
dotenv.cabal
spec/Configuration/Dotenv/Scheme/ParseSpec.hs
spec/Configuration/Dotenv/SchemeSpec.hs
spec/fixtures/.scheme.yml
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Scheme.hs
src/Configuration/Dotenv/Scheme/Helpers.hs
src/Configuration/Dotenv/Scheme/Types.hs

Changes in the safe wrapper

---

CHANGELOG.md
dotenv.cabal

* Update the PVP to change the documentation displayed on hackage
@juanpaucar Could you take a look, please?

Update PVP - Minor change

---

CHANGELOG.md
dotenv.cabal
src/Configuration/Dotenv/Parse.hs

https://github.com/fpco/stackage/issues/3159

Support `megaparsec` >= 6.4.0

---

.travis.yml
CHANGELOG.md
dotenv.cabal
spec/Configuration/Dotenv/SchemeSpec.hs
src/Configuration/Dotenv/Scheme.hs
src/Configuration/Dotenv/Scheme/Types.hs

Don't allow duplicated values in the schema configuration

---

.travis.yml

Support for GHC 8.4.1.
@juanpaucar Could you take a look, please?

Add GHC 8.4.1 to .travis.yml

---

CHANGELOG.md
dotenv.cabal
stack.yaml

@juanpaucar Do you think changing the process bounds will help fix problem with stackage? I'm not sure if there are problems with the previous version.

Change bounds for process

---

LICENSE
README.md
dotenv.cabal
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Parse.hs
src/Configuration/Dotenv/ParsedVariable.hs
src/Configuration/Dotenv/Scheme.hs
src/Configuration/Dotenv/Scheme/Helpers.hs
src/Configuration/Dotenv/Scheme/Parser.hs
src/Configuration/Dotenv/Scheme/Types.hs
src/Configuration/Dotenv/Text.hs
src/Configuration/Dotenv/Types.hs

I set the license as a date range as we have in other [projects](https://github.com/stackbuilders/hapistrano/blob/master/LICENSE#L1). Also, the start date was in `2015` as this [commit](https://github.com/stackbuilders/dotenv-hs/commit/0f49e3e6c711c3166ef9215f224bde1abaae7524#diff-9879d6db96fd29134fc802214163b95aR1) shows.

Update license date range

---

.travis.yml
.travis/ghcup.sh
CHANGELOG.md
dotenv.cabal

This change updates the travis configuration to test the new version.
Fixes #118

Extend ghc support to 8.8 and 8.10

---

.github/workflows/release-gh.yml

This PR sets up GH actions to create a release on Github and upload the assets for Linux and MacOS versions of the library.

Release to Github workflow

---

.github/workflows/build-and-test.yml
CHANGELOG.md
app/Main.hs
dotenv.cabal
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv/Environment.hs
src/Configuration/Dotenv/Parse.hs
src/Configuration/Dotenv/ParsedVariable.hs
src/Configuration/Dotenv/Scheme/Helpers.hs
src/Configuration/Dotenv/Scheme/Parser.hs
src/Configuration/Dotenv/Scheme/Types.hs
stack.yaml
stack.yaml.lock

- Removes the 7.10.3 job from the CI.
- Updates the base version.
- Removes CPP code that is no longer needed
- Updates the changelog and the version.

Drop support GHC 7.10

---

CHANGELOG.md
dotenv.cabal
stack.yaml

This PR address #139
optparse-applicative Upgraded to 0.17

[#139] Upgrade optparse-applicative to 0.17

---

dotenv.cabal

* Remove `transformers` from library, executable and testing library.

[NO ISSUE] Remove dependency

---

LICENSE
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md

Changes:
- Include contributing guidelines
- Update README.md
- Update License

Change docs

---

README.md
app/Main.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Types.hs

This PR implements the solution for #147

feat: No duplicates option 

---

CHANGELOG.md
README.md
dotenv.cabal

- Update README
- Update cabal
- Update CHANGELOG

bump version 0.11.0.0

---

CHANGELOG.md
dotenv.cabal
spec/Configuration/Dotenv/ParseSpec.hs
spec/Configuration/Dotenv/TextSpec.hs
spec/Configuration/DotenvSpec.hs
src/Configuration/Dotenv.hs
src/Configuration/Dotenv/Internal.hs
src/Configuration/Dotenv/ParsedVariable.hs

- Remove `src` from test-suite
- Remove `other_modules` from test-suite
- Reduce dependencies in test-suite
- Expose internal modules
- Document new exposed types and functions

chore: Expose new modules and update cabal file

---

.github/workflows/build.yml
.github/workflows/publish.yml

- `s/haskell\/actions/haskell-actions`

fix: Replace haskell/actions with haskell-actions

---

.github/workflows/release.yml
.releaserc
dotenv.cabal

Hi,
This PR targets #196 and adds configuration according to [this change](https://github.com/stackbuilders/hspec-golden/commit/a7b2b07c7b38dd39fefef9f86e545771e2e90f98).
Let me know if anything needs changing :).

Add semantic release config
